[versions]
shadow = "9.6.1"
runPaper = "3.1.0"

paper = "26.3.build.26-alpha"

placeholderapi = "2.12.3"
packetevents = "2.13.0"
tab = "6.1.2"
skinsrestorer = "15.12.5"
caffeine = "3.2.4"
entitylib = "3.3.7-SNAPSHOT"
bstats = "3.2.1"

junit-jupiter = "5.14.4"

[libraries]
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

placeholderapi = { module = "me.clip:placeholderapi", version.ref = "placeholderapi" }
packetevents = { module = "com.github.retrooper:packetevents-spigot", version.ref = "packetevents" }
tab = { module = "com.github.NEZNAMY:TAB-API", version.ref = "tab" }
skinsrestorer = { module = "net.skinsrestorer:skinsrestorer-api", version.ref = "skinsrestorer" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
entitylib = { module = "io.github.tofaa2:spigot", version.ref = "entitylib" }
bstats = { group = "org.bstats", name = "bstats-bukkit", version.ref = "bstats" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }
